spring:
  application:
    name: soongan-backend
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    include: jasypt, db
  cloud:
    gcp:
      project-id: ENC(mONxGermhM5bU+13G8tPHg==)
      credentials:
        location: ENC(LQslraULdvQzT5CSqfOM6ywMu8A+N+un9mgO9pspoBeH9t71fU2y/iW6eHMszUDT)
      storage:
        bucket: ENC(mONxGermhM5bU+13G8tPHg==)

springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true

server:
  port: 8080

oauth2:
  android:
    google:
      client-id: ENC(ZWeHYcVoYY4PbLoeWPVIrOvsfrGjbwtqAPQsQi7Yox9LwVTjQi89IJnuqFonyGi5/y1CwrPXzC1OKnGWRSR85nPrWyaIJ/zJx8YUMb5gPNp7S7oM/3/IsA==)
  ios:
    google:
      client-id: ENC(teK8fJZvVa2yHpTi/sBcuXMF7vrnsbrZtGMD5fkycc+a7s/Xjz0TTD8mCdgNLPBldzkTfewAINd0r/IlidxUew/3KwNvm3Gf0KhGrDkksT36Fra0RZqPPQ==)


jwt:
  secret: ENC(Uet8sXoFY7S7ZDmqS2RuCOhRbluWH1jyGlNbOo3G3kPlxipkxqmvo2IKeaU2Hv+X)

firebase:
  project-id: ENC(5YLSshIxITz1cQ1o2Dsf62PVAryHEo1W)
  keypath: ENC(hN8sOLKoQ/s2TyXj+DKxmSexUv5jT2HfT+G3wqCrhOMcTD2kNXq+a02VkVu2uBIpoE3t/3HmjOgK/y9Bon0p6A==)