spring:
  application:
    name: soongan-api
  config:
    import:
      - optional:soongan-redis.yml
      - optional:soongan-persistence.yml
      - optional:soongan-support.yml
      - optional:soongan-web.yml
      - optional:soongan-kafka.yml

server:
  port: 8080
  servlet:
    context-path: /api

oauth2:
  android:
    google:
      client-id: ENC(X5Fveb+YUEGGunq37whc6q5j7cnkh+EFW7AATZMWw7zn8Y/fOWzYwu8kYLogfMhTZ6+nx16AyGPIzEKytaT9oTLpDovOrPfZTdwzarQUeJsCDhIHuKEzRQ==)
  ios:
    google:
      client-id: ENC(ULUYhauNR09LtLAblSQowxZLT/3Y7ujh11fIaghgFUlVYrXLnPrzQpvCDzDZJ87FU80KZfJGkpPe+VqKZad4xUIC3eA2U4yc3QVlyNvsMHxHkkVBWXjLTg==)