spring:
  application:
    name: soongan-api
  config:
    import:
      - optional:soongan-redis.yml
      - optional:soongan-persistence.yml
      - optional:soongan-support.yml
      - optional:soongan-web.yml
      - optional:soongan-kafka.yml

server:
  port: ${SERVER_PORT}

oauth2:
  android:
    google:
      client-id: ${OAUTH2_ANDROID_GOOGLE_CLIENT_ID}
  ios:
    google:
      client-id: ${OAUTH2_IOS_GOOGLE_CLIENT_ID}

firebase:
  project-id: ${FCM_FIREBASE_PROJECT_ID}
  key-json-string: ${FCM_FIREBASE_KEY_JSON}