spring:
  application:
    name: soongan-consumer
  config:
    import:
      - optional:soongan-persistence.yml
      - optional:soongan-support.yml
      - optional:soongan-kafka.yml

server:
  port: 8081