spring:
  application:
    name: soongan-consumer
  config:
    import:
      - optional:soongan-persistence.yml
      - optional:soongan-support.yml
      - optional:soongan-kafka.yml
      - optional:soongan-web.yml
      - optional:soongan-redis.yml

  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081

firebase:
  project-id: ENC(YnIuCYTbbvKguEmV59GFjmlvT5k7yE0W)
  keypath: ENC(HrvzYIU+FVnEgO9n+2c9wRSeDAIPDzv7lkd182jCK7rRYxNvyJNBSvf15copCykm5t3wxfrTWbOxua4YN0+ydjSs9FD6keuW)