name: Build with Infisical Secrets

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Infisical CLI
        run: |
          curl -1sLf \
          'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' \
          | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Debug Infisical Environment Variables
        run: |
          echo "INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN_API_DEV }}" | sed 's/./& /g'
          echo "INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID_API }}" | sed 's/./& /g'

      - name: Authenticate Infisical
        run: |
          export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN_API_DEV }}
          export INFISICAL_PROJECT_ID=${{ secrets.INFISICAL_PROJECT_ID_API }}
          infisical auth --token $INFISICAL_TOKEN

      - name: Build with Gradle and Infisical
        run: |
          export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN_API_DEV }}
          export INFISICAL_PROJECT_ID=${{ secrets.INFISICAL_PROJECT_ID_API }}
          infisical run --env=dev -- ./gradlew :soongan-api:build
