name: Build And Test On Pull Request

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    if: github.repository_owner == 'captures-2024'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew :soongan-api:build
